name: test_reader(Unittesting)

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9",]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test class Reader with unittest
        run: python -m unittest livelib/tests/test_reader.py
      - name: Upload artifact .log
        uses: actions/upload-artifact@v3
        with:
          name: test_reader.log
          path: livelib/tests/logs/test_reader.log
          retention-days: 3