name: test_webconnection(Unittesting)

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9",]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test class WebConnection with unittest
        run: python -m unittest livelib/tests/test_webconnection.py
      - name: Archive log file
        uses: actions/upload-artifact@v3
        with:
          name: log_for_test_web_connection
          path: livelib/tests/log.log
      - name: Archive log file 2
        uses: actions/upload-artifact@v3
        with:
          name: log2_for_test_web_connection
          path: livelib/log.log

